### ISSUE TITLE
难以理解的动态权重

### ISSUE THREAD

**Issue by yyds-xtt** [Malena-yy/moddpg#2]
你的代码写的   r += (args.w_dc * dr + args.w_eh * (cu + eh) - args.w_ec * ec)
你的这个权重是固定的啊
和你论文里表述不一样啊

In our setting, all of the weight parameters are chosen in the interval [0.0, 1.0] according to the importance preference of each attribute. With the target network, the target value yi is calculated as following.

**Comment by Malena-yy** [comment]
你好，权重的设置一直是超参数，代码和论文表述不一致的地方在于论文中对各部分奖励的缩放处理是放在rdc(t), reh(t), rec(t)的设计上，核心是希望各部分奖励能够处于同一数量级，之后再通过权重的调整来控制各部分奖励在总奖励中的比重。

**Comment by yyds-xtt** [comment]
这个权重 是实时变化的。你这种加权和的方式，还是单目标，不是多目标

**Comment by yyds-xtt** [comment]
MODDPG 和ddpg有什么区别呢？max v(t),θ(t)(Rsum ,Eh total, − Ec total) 只是这个定义不一样吗？

**Comment by yyds-xtt** [comment]
Dynamic Weights in Multi-Objective Deep Reinforcement Learning，你看过这个论文吗

**Comment by yyds-xtt** [comment]
Dynamic Weights in Multi-Objective Deep Reinforcement Learning，你是按照这个论文做的吗，但是你也没引用。为什么你这个方法直接就行了，依据什么？自创的吗

**Comment by Malena-yy** [comment]
你好，文章并没有提到dynamic weights～
