### ISSUE TITLE
飞行时间问题

### ISSUE THREAD

**Issue by jmm1999** [Malena-yy/moddpg#3]
你好，我想问一下关于代码中的飞行时间问题，速度不超过20m/s，飞行时间设为1s，从一个目标设备怎么飞到另一个目标设备，这一部分不太理解

**Comment by Malena-yy** [comment]
你好，仿真设置整个飞行周期为10 minutes, 飞行时间设为1s为当前飞行决策作用的时间，每1s更新飞行角度和方向。
